---
apiVersion: resource.k8s.io/v1beta1
kind: DeviceClass
metadata:
  name: rdma
spec:
  selectors:
    - cel:
        expression: device.driver == "dra.net"
    - cel:
        expression: device.attributes["dra.net"].rdma
---
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  name: rdma-net-template
spec:
  spec:
    devices:
      requests:
      - name: rdma-net-interface
        deviceClassName: rdma
        selectors:
        - cel:
            expression: device.attributes["dra.net"].kind == "network"
---
apiVersion: v1
kind: Service
metadata:
  name: nccl-workload
spec:
  selector:
    name: nccl-workload
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nccl-workload
  labels:
    name: nccl-workload
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nccl-workload
  template:
    metadata:
      labels:
        name: nccl-workload
    spec:
      containers:
        - image: us-docker.pkg.dev/gce-ai-infra/gpudirect-gib/nccl-plugin-gib-diagnostic:v1.0.5
          name: test
          resources:
            requests:
              cpu: 150m
          volumeMounts:
            - name: library-dir-host
              mountPath: /usr/local/nvidia
            - name: gib
              mountPath: /usr/local/gib
            - name: shared-memory
              mountPath: /dev/shm
          env:
            - name: LD_LIBRARY_PATH
              value: /usr/local/nvidia/lib64
          resources:
            limits:
              nvidia.com/gpu: 8
          command: ["/bin/bash", "-c"]
          args:
            - |
              /scripts/container_entry.sh shell
              source /usr/local/gib/scripts/set_nccl_env.sh
              sleep infinity
      resourceClaims:
      - name: rdma-net-interface
        resourceClaimTemplateName: rdma-net-template
      volumes:
        - name: library-dir-host
          hostPath:
            path: /home/kubernetes/bin/nvidia
        - name: gib
          hostPath:
            path: /home/kubernetes/bin/gib
        - name: shared-memory
          emptyDir:
            medium: "Memory"
            sizeLimit: 250Gi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                name: nccl-workload
            topologyKey: kubernetes.io/hostname
---
